### ISSUE TITLE
PIN entry after reconnecting device

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-onboarding#10]
T1 with PIN already set

Browser does not display a PIN entry modal after device was reconnected after onboarding step PIN setup.

**Comment by mroz22** [comment]
Should be solved here https://github.com/trezor/trezor-onboarding/commit/674cb490f10827381cdef9386b637f17a6552a77

**Comment by sorooris** [comment]
PIN entry is displayed, test OK.

![image](https://user-images.githubusercontent.com/10185314/55721489-c8b1ad80-5a03-11e9-9dd7-7c502f761c6a.png)
