### ISSUE TITLE
Seed recovery - model TT frozen on recovery confirmation screen

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-onboarding#11]
TT

Device screen displays a prompt with the message "Do you really want to recover the device?" and becomes irresponsive, the page then waits for the input from the device and displays a "Complete action on your device" message. Going back on the step progress bar keeps the prompt displayed. Page refresh helped until the same step was reached.

Could not reproduce again (!).

![image](https://user-images.githubusercontent.com/10185314/55559157-ef16d680-56ed-11e9-89d9-0ec484b88f82.png)
![image](https://user-images.githubusercontent.com/10185314/55559173-f6d67b00-56ed-11e9-9c6b-0c162593d3db.png)

**Comment by sorooris** [comment]
As mentioned in the description, could not reproduce again.

**Comment by mroz22** [comment]
This probably does not belong to this project.

**Comment by mroz22** [comment]
Closing, resolve with firmware team
