### ISSUE TITLE
Initialized device (bootloader-wiped) detected as in bootloader mode

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-onboarding#14]
https://onboarding-dev.trezor.io/
TT (btl 2.0.3, fw 2.1.0)

Device is detected as in bootloader mode after complete wipe (trezorctl wipe_device --bootloader)
![image](https://user-images.githubusercontent.com/10185314/55710547-21c11780-59eb-11e9-83a2-43cea83ea1a7.png)

**Comment by mroz22** [comment]
Try again, it was possibly fixed by https://github.com/trezor/trezor-onboarding/commit/f533d4b72d35009edafd2980cefbd829ac6e4e17

**Comment by sorooris** [comment]
@mroz22 retest NOK, the problem still persists.

**Comment by sorooris** [comment]
retest OK
