### ISSUE TITLE
Seed recovery - clicking the seed word input deletes the unfinished word

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-onboarding#15]
https://onboarding-dev.trezor.io
T1 (fw 1.8.0)

Clicking the seed word input deletes the unfinished word.

![image](https://user-images.githubusercontent.com/10185314/55720111-4f648b80-5a00-11e9-9b1b-52f1bbc9c01e.png)

**Comment by mroz22** [comment]
Trezor-wallet now works in the same way. Not sure if this is a bug or a feature :D.

**Comment by mroz22** [comment]
Ok, with guys, we agreed this is a feature.
