### ISSUE TITLE
Backup icons

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-onboarding#18]
People dont like to read, we want some descriptive icons for what not to do with your seed 

- no photos
- no storing in pc / mobile
- no uploading to cloud.

**Comment by vitavalka** [comment]
Proposed icons, in conservative black or disruptive red color:
<img width="393" alt="icons-no-photo" src="https://user-images.githubusercontent.com/2325142/56088218-464e4100-5e7c-11e9-9b82-b8f36e21c5b8.png">

**Comment by mroz22** [comment]
Thanks, I like this subset 

![image](https://user-images.githubusercontent.com/30367552/56134018-fa8bbc80-5f8d-11e9-98e0-1602c7cd5fb1.png)

Could you export it somehow?

**Comment by vitavalka** [comment]
Here you are. They are each SVG file in a 24px x 24px boundary box → [Icons-Assets.zip](https://github.com/trezor/trezor-onboarding/files/3080229/Icons-Assets.zip)
