### ISSUE TITLE
Mobile design for top navbar

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-onboarding#20]
Here we have how it could look like 

https://projects.invisionapp.com/d/main#/console/16688993/353302933/preview

Note we are waiting for trezor-ui-components guys. They are preparing top navbar as a component.

**Comment by vitavalka** [comment]
As for functionality, few notes:
- the dark menu can slide from the right edge of screen
- tapping on anywhere outside of the menu (left two thirds) closes the menu by sliding back to right and then opacity of the screen content goes back to original
- public link to the InVision screen: https://invis.io/8WQFYCPEJA2#/353302933_iPhone_Menu
- flag icons in SVG are here: https://www.flaticon.com/packs/international-flags

**Comment by mroz22** [comment]
Now resolved using Header from trezor-ui-components
