### ISSUE TITLE
Not saved warning

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-onboarding#32]
After end of onboarding you are asked if you really want to leave to wallet and changes may not be saved.
This can be really confusing for first time users

![onb2](https://user-images.githubusercontent.com/31506317/56572535-8b325000-65bf-11e9-8399-97c74d9e205c.png)

**Comment by mroz22** [comment]
This is a bug. I should deregister the event listener here.

**Comment by mroz22** [comment]
Should be fixed now
