### ISSUE TITLE
Not able to change PIN

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-onboarding#38]
I'm not able to change PIN code if I decided to change it during onboarding.

It only says Purfect! Your device is now secured by pin. Continue

![Screenshot from 2019-04-29 14-35-30](https://user-images.githubusercontent.com/31506317/56896463-14e49080-6a8c-11e9-98e0-72f9dd073039.png)

**Comment by bosomt** [comment]
and of course same for passphrase

**Comment by mroz22** [comment]
> and of course same for passphrase

You dont set passphrase in the onboarding process.

> I'm not able to change PIN code if I decided to change it during onboarding

I ll discuss this with UX guys.

**Comment by mroz22** [comment]
![image](https://user-images.githubusercontent.com/30367552/56902211-0f8e4280-6a9a-11e9-8f58-d1697a401c6e.png)

**Comment by mroz22** [comment]
rejected.
