### ISSUE TITLE
CTA placement

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-onboarding#43]
There are inconsistencies in buttons order now. Lets unify it. But how. 

![image](https://user-images.githubusercontent.com/30367552/57353429-bd6bb200-7168-11e9-806a-17f5f87b30e5.png)

![image](https://user-images.githubusercontent.com/30367552/57353445-cc526480-7168-11e9-9445-2585a8dccf94.png)

![image](https://user-images.githubusercontent.com/30367552/57353482-eb50f680-7168-11e9-955e-4aa61a17cc85.png)

![image](https://user-images.githubusercontent.com/30367552/57353500-fc016c80-7168-11e9-9564-5f84e29d1ff3.png)

![image](https://user-images.githubusercontent.com/30367552/57353557-2b17de00-7169-11e9-9713-ccbb6fa3629a.png)

CTA should be on the left in general?

**Comment by vitavalka** [comment]
The main (recommended) action should be the full color one, and on the right side. The least recommended "safety" action such as BACK or SKIP should be gray, linear and on the left. Anything else in between these main constraints.

**Comment by mroz22** [comment]
implemented in fd9902a8ef03047e8f8355db7af03a7d61c8f61a
