### ISSUE TITLE
Unify text-align

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-onboarding#6]
Center or justify?

**Comment by mroz22** [comment]
Example of center 

![image](https://user-images.githubusercontent.com/30367552/55721542-e7b03f80-5a03-11e9-87a1-1c70ba3fc218.png)

Example of justify

![image](https://user-images.githubusercontent.com/30367552/55721635-1b8b6500-5a04-11e9-8908-fdfd2dbb970a.png)

**Comment by vitavalka** [comment]
Definitely the left aligned text is better for readability (finding line beginnings). I would also try to make the titles short and juicy, whenever it is possible. This one could be:
- **Seed — the most important thing**
- **Seed is critical, device is not**
- **Seed is a key to your device**

**Comment by mroz22** [comment]
I ended up using centered text align. We may revisit this later.
