### ISSUE TITLE
not able to skip PIN setup

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-onboarding#7]
I'm not able to skip PIN setup dialogue, even PIN code protection is optional.

![Screenshot_20190404_115424](https://user-images.githubusercontent.com/31506317/55546894-77867e80-56d0-11e9-96c6-6ee58aa82168.png)

**Comment by bosomt** [comment]
and it's same for custom Trezor name.
I'm not able to skip it ;)

**Comment by mroz22** [comment]
And should it be 
1) skip the entire security setu procedure or
1) skip only one step?

**Comment by bosomt** [comment]
one step, there is only one option
set pin
there is no way to skip it

**Comment by bosomt** [comment]
same for renaming your device, 
there is no way to skip it
is it bug or feature ? :)

**Comment by mroz22** [comment]
should be solved in 0c9eede26095de3658354ac1c0872b3cc5c8d352
