### ISSUE TITLE
Unacquired device error

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-onboarding#8]
T1, TT

Device that is used in another window fails the onboarding process on step 3 (Bridge, connecting device) and displays an error message.

![image](https://user-images.githubusercontent.com/10185314/55546941-8d943f00-56d0-11e9-8e57-db6a0669dd68.png)

Console error log attached.
[unacq.txt](https://github.com/trezor/trezor-onboarding/files/3042935/unacq.txt)

**Comment by mroz22** [comment]
should be fixed in https://github.com/trezor/trezor-onboarding/commit/10a7614da7dca7999bf18c2838523e4b54c12811
