### ISSUE TITLE
No timeout after Bridge not detected

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-onboarding#9]
Step 3 after browser detects that Bridge isn't installed.

Browser keeps checking the connection to Bridge and does not stop.
Expected behaviour would be an error or a prompt after x failed attempts or timeout.

![image](https://user-images.githubusercontent.com/10185314/55553351-3ac28380-56e0-11e9-903c-9ef2e94c9ba7.png)

**Comment by mroz22** [comment]
this is trezor-connect implementation, so it is not in the scope of this project. I can not affect it.
